BirdFarmShop/Pages/BirdDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BusinessObjects.Models;
using Services.IServices;

namespace BirdFarmShop.Pages
{
    public class BirdDetailsModel : PageModel
    {
        private readonly IBirdService _birdService;
        private readonly ICommentService _commentService;

        public BirdDetailsModel(IBirdService birdService, ICommentService commentService)
        {
            _birdService = birdService;
            _commentService = commentService;
        }
        [BindProperty]
        public Bird Bird { get; set; } = default!;
        public IList<TblComment> TblComment { get; set; } = default!;
        [BindProperty]
        public TblComment Comment { get; set; } = default!;
        public int UserID { get; private set; }

        public IActionResult OnGet(int? id)
        {

            var bird = _birdService.GetBirdByID(id.Value);
            var comment = _commentService.GetAllCommnets().Where(b => b.Bird.BirdId == id).ToList();
            TblComment = comment;
            if (bird == null)
            {
                return NotFound();
            }
            else 
            {
                Bird = bird;
            }
            return Page();
        }
        public IActionResult OnPostAsync()
        {
            try
            {
                UserID = (int)HttpContext.Session.GetInt32("UserID")!;
            }
            catch
            {
                return RedirectToPage("/Login");
            }
            if (string.IsNullOrEmpty(Comment.Content) || string.IsNullOrEmpty(Comment.Rating.ToString()) || Comment.Rating < 0 || Comment.Rating > 5)
            {
                OnGet(Bird.BirdId);
                return Page();
            }
            var comment = new TblComment()
            {
                UserId = UserID,
                BirdId = Bird.BirdId,
                CommentDate = DateTime.Now,
                Content = Comment.Content,
                Rating = Comment.Rating,
            };
            _commentService.AddNew(comment);

            OnGet(Bird.BirdId);
            return Page();
        }
    }
}

BirdFarmShop/Pages/Cart.cshtml.cs
using BirdFarmShop.Entities;
using BirdFarmShop.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.IServices;

namespace BirdFarmShop.Pages
{
    public class CartModel : PageModel
    {
        private readonly IBirdService _birdService;
        public CartModel(IBirdService birdService) 
        {
            _birdService = birdService;
        }
        public List<Item> cart { get; set; }
        public decimal?  Total { get; set; }

        public IActionResult OnGet()
        {
            try
            {
                cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                if(cart == null) 
                {
                    return RedirectToPage("CartEmpty");
                }
                Total = cart.Sum(i => i.bird.Price * i.Quantity);
            }
            catch
            {
                return NotFound();
            }
            return Page();
        }

        public IActionResult OnGetAddToCart(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<Item>();
                cart.Add(new Item
                {
                    bird = _birdService.GetBirdByID(id),
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                int index = Exists(cart, id);
                if (index == -1)
                {
                    cart.Add(new Item
                    {
                        bird = _birdService.GetBirdByID(id),
                        Quantity = 1
                    });
                }
                else
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("Cart");
        }
        public IActionResult OnGetDelete(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Cart");
        }

        public IActionResult OnPostUpdate(int[] quantities)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            try
            {
                for (var i = 0; i < cart.Count; i++)
                {
                    cart[i].Quantity = quantities[i];
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                return RedirectToPage("Cart");
            }
            catch
            {
                return RedirectToPage("Cart");
            }
            
        }

        private int Exists(List<Item> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].bird.BirdId == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

BirdFarmShop/Pages/CartEmpty.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BirdFarmShop.Pages
{
    public class CartEmptyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BirdFarmShop/Pages/CheckOut.cshtml.cs
using BirdFarmShop.Entities;
using BirdFarmShop.Helpers;
using BusinessObjects.DTOs;
using BusinessObjects.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Services.IServices;
using Services.UnitOfWork;

namespace BirdFarmShop.Pages
{
    public class CheckOutModel : PageModel
    {
        private readonly IOrderService _orderService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IOrderDetailService _orderDetailService;
        private readonly IBirdService _birdService;
        private readonly IUserService _userService;
        public CheckOutModel(IOrderService orderService, IUnitOfWork unitOfWork, IOrderDetailService orderDetailService, IBirdService birdService, IUserService userService) 
        {
            _orderDetailService = orderDetailService;
            _unitOfWork = unitOfWork;
            _birdService = birdService;
            _orderService = orderService;
            _userService = userService;
        }

        [BindProperty]
        public UserDTO TblUser { get; set; } = default!;
        public List<Item> cart { get; set; }
        public decimal? Total { get; set; }
        public string Msg { get; private set; }
        public string EmptyMsg { get; private set; }
        public int UserId;
        public string errorQuantity;

        public IActionResult OnGet()
        {
            try
            {
                UserId = (int)HttpContext.Session.GetInt32("UserID")!;
            }
            catch
            {
                Msg = "You must be login to continute this action";
                cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                return Page();
            }
            var tbluser = _userService.GetUserDTOById(UserId);
            if (tbluser == null)
            {
                return NotFound();
            }
            TblUser = tbluser;
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            return Page();
        }
        public IActionResult OnPost()
        {
            try
            {
                UserId = (int)HttpContext.Session.GetInt32("UserID")!;
            }catch
            {
                return RedirectToPage("Login");
            }
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if(cart.Count <= 0)
            {
                EmptyMsg = "You do not have any Bird in your Cart";
                return Page();
            }
            Total = cart.Sum(i => i.bird.Price * i.Quantity);

            var order = new TblOrder()
            {
                UserId = UserId,
                ReasonContent = $"Số điện thoại người nhận: {TblUser.Phone},Tên Người nhận: {TblUser.FullName}",
                TypeOrder = "Shopping",
                OrderStatus = "Processing",
                StartDate = DateTime.Now,
                EndDate = null,
                ShipAddress = TblUser.UserAddress!
            };
            _orderService.AddNewOrder(order);

            foreach (var item in cart)
            {
                var orderDetail = new TblOrderDetail()
                {
                    OrderId = order.OrderId,
                    BirdId = item.bird.BirdId,
                    Quantity = item.Quantity,
                    TotalPrice = item.Quantity * item.bird.Price,
                    CostsIncurred = ""
                };
                var checkQuantity = _birdService.GetBirdByID(item.bird.BirdId);
                if (checkQuantity != null && checkQuantity.Quantity > 0 && checkQuantity.Quantity > item.Quantity) 
                {
                    checkQuantity.Quantity -= item.Quantity;
                    _unitOfWork.Update(checkQuantity);
                    _unitOfWork.SaveChanges();
                }
                else
                {
                    errorQuantity = "This Bird is out of Stock";
                    return Page();
                }
                _orderDetailService.AddNewOrderDetail(orderDetail);
            }
            HttpContext.Session.Remove("cart");

            return RedirectToPage("ShowAllBirds");
        }
    }
}

BirdFarmShop/Pages/HomePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BirdFarmShop.Pages
{
    public class HomePageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BirdFarmShop/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using BusinessObjects.Models;
using Repositories.IRepository;
using Services.IServices;

namespace BirdFarmShop.Pages
{
    public class LoginModel : PageModel
    {

        private readonly IUserService _userService;
        public LoginModel( IUserService userService)
        {
            _userService = userService;
        }

        [BindProperty]
        public TblUser user { get; set; } = default!;
        public string ErrorMessage { get; private set; }

        public IActionResult OnPost()
        {
            
            if(!string.IsNullOrWhiteSpace(user.UserName) && !string.IsNullOrWhiteSpace(user.Pass))
            {
                try
                {
                    var check = _userService.checkLogin(user.UserName, user.Pass);
                    if (check != null)
                    {
                        if(check.UserStatus != true)
                        {
                            ErrorMessage = "You are not allowed access into system";
                            return Page();
                        }
                        if (check.RoleId.Equals("US"))
                        {
                            try
                            {
                                var cart = HttpContext.Session.GetString("cart");
                                if (cart != null)
                                {
                                    HttpContext.Session.SetInt32("UserID", check.UserId);
                                    return RedirectToPage("Cart");
                                }
                            }
                            catch
                            {
                                HttpContext.Session.SetInt32("UserID", check.UserId);
                                return RedirectToPage("HomePage");
                            }
                            HttpContext.Session.SetInt32("UserID", check.UserId);
                            return RedirectToPage("HomePage");
                        }
                        if (check.RoleId.Equals("AD"))
                        {
                            HttpContext.Session.SetInt32("UserID", check.UserId);
                            HttpContext.Session.SetString("isAdmin", check.RoleId);
                            return RedirectToPage("Admin/UserManagement/ShowUserList");
                        }
                        if (check.RoleId.Equals("MN"))
                        {
                            HttpContext.Session.SetInt32("UserID", check.UserId);
                            HttpContext.Session.SetString("isManager", check.RoleId);
                            return RedirectToPage("Manager/StaffManagement/Index");
                        }
                        if (check.RoleId.Equals("ST"))
                        {
                            HttpContext.Session.SetInt32("UserID", check.UserId);
                            HttpContext.Session.SetString("isStaff", check.RoleId);
                            return RedirectToPage("Staff/BirdManagement/Index");
                        }
                    }
                    ErrorMessage = "Incorect User Name or Password Please Try Again";
                    return Page();
                }
                catch
                {
                    ErrorMessage = "Incorect User Name or Password Please Try Again";
                    return Page();
                }
            }
            return Page();
        }
    }
}

BirdFarmShop/Pages/LoginGoogle.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BirdFarmShop.Pages
{
    public class LoginGoogleModel : PageModel
    {
        public IActionResult OnGet()
        {
            var authenticationProperties = new AuthenticationProperties
            {
                RedirectUri = Url.Page("/LoginGoogleCallBack"),
            };
            return Challenge(authenticationProperties, "Google");
        }
    }
}

BirdFarmShop/Pages/LoginGoogleCallBack.cshtml.cs
using BusinessObjects.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories.IRepository;
using System.Security.Claims;

namespace BirdFarmShop.Pages
{
    public class LoginGoogleCallBackModel : PageModel
    {
        private readonly IUserRepository _userRepository;
        private readonly BirdFarmShopContext _birdFarmShopContext;
        public LoginGoogleCallBackModel(IUserRepository userRepository, BirdFarmShopContext birdFarmShopContext)
        {
            _userRepository = userRepository;
            _birdFarmShopContext = birdFarmShopContext;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            var authenticateResult = await HttpContext.AuthenticateAsync("Google");

            if (authenticateResult.Succeeded)
            {
               
                var userFullName = authenticateResult.Principal.FindFirstValue(ClaimTypes.Name);
                var userEmail = authenticateResult.Principal.FindFirstValue(ClaimTypes.Email);
                var address = authenticateResult.Principal.FindFirstValue(ClaimTypes.StreetAddress);
                var district = authenticateResult.Principal.FindFirstValue(ClaimTypes.Locality);
                var phone = authenticateResult.Principal.FindFirstValue(ClaimTypes.HomePhone);
                var image = authenticateResult.Principal.FindFirstValue("image");

                var checkUserExisted = _birdFarmShopContext.TblUsers.Where(u => u.Email.Equals(userEmail)).SingleOrDefault();

                if (checkUserExisted != null)
                {
                    HttpContext.Session.SetInt32("UserID",checkUserExisted.UserId);
                    return RedirectToPage("User/Profile");
                }
                TblUser user = new TblUser()
                {
                    FullName = userFullName,
                    Email = userEmail,
                    RoleId = "US",
                    UserAddress =address,
                    UserStatus = true,
                    Phone = phone,
                    Pass ="@1"
                };
                _birdFarmShopContext.TblUsers.Add(user);
                _birdFarmShopContext.SaveChanges();

                var check = _userRepository.GetUserByEmail(user.Email);
                HttpContext.Session.SetInt32("UserID", check.UserId);
                return RedirectToPage("User/Profile");
            }
            else
            {
                // Xử lý lỗi đăng nhập Google ở đây

                return RedirectToPage("/Login");
            }
        }
    }
}

BirdFarmShop/Pages/Cart.cshtml
@page
@model BirdFarmShop.Pages.CartModel
@{
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/cart.css">
    <title>Cart</title>
</head>
<body>
    <div class="cart_section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="cart_container">
                        <div class="cart_title">Shopping Cart<small> (1 item in your cart) </small></div>
                        <div class="cart_items">
                            <ul class="cart_list">
                                <form method="post" asp-page="cart" asp-page-handler="update">

                                    @foreach (var item in Model.cart)
                                    {
                                    <li class="cart_item clearfix">
                                        <div class="cart_item_image"><img src="@item.bird.Image" alt=""></div>
                                        <div class="cart_item_info d-flex align-content-center flex-md-row justify-content-between">
                                            <div class="cart_item_name cart_info_col">
                                                <div class="cart_item_title">Name</div>
                                                <div class="cart_item_text">@item.bird.BirdName</div>
                                            </div>
                                            <div class="cart_item_quantity cart_info_col">
                                                <div class="cart_item_title">Quantity</div>

                                                <div class="cart_item_text"><input type="number" name="quantities" value="@item.Quantity" min="1" style="width: 50px;" /></div>
                                            </div>
                                            <div class="cart_item_price cart_info_col">
                                                <div class="cart_item_title">Price</div>
                                                <div class="cart_item_text">@item.bird.Price VNĐ</div>
                                            </div>
                                            <div class="cart_item_total cart_info_col">
                                                <div class="cart_item_title">Sub Total</div>
                                                <div class="cart_item_text">@(item.bird.Price * item.Quantity) VNĐ</div>
                                            </div>

                                            <div class="cart_item_total cart_info_col">
                                                <div class="cart_item_title"></div>
                                                <div class="cart_item_text"><input type="submit" value="Update" /><i class="fa-solid fa-code-compare"></i></div>
                                            </div>
                                            <div class="cart_item_total cart_info_col">
                                                <div class="cart_item_title"></div>
                                                <div class="cart_item_text"><a asp-page="cart" asp-page-handler="delete" asp-route-id="@item.bird.BirdId"><i class="fa-solid fa-trash"></i></a></div>
                                            </div>
                                        </div>
                                    </li>
                                    }
                                </form>
                            </ul>
                        </div>
                        <div class="order_total">
                            <div class="order_total_content text-md-right">
                                <div class="order_total_title">Order Total:</div>
                                <div class="order_total_amount">@Model.Total VNĐ</div>
                            </div>
                        </div>
                        <div class="cart_buttons">
                            <a asp-page="ShowAllBirds"><button type="button" class="button cart_button_clear">Continue Shopping</button></a>
                            <a asp-page="CheckOut"><button type="button" class="button cart_button_checkout">Buy</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://kit.fontawesome.com/6bf3556146.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</body>

BirdFarmShop/Pages/CartEmpty.cshtml
@page
@model BirdFarmShop.Pages.CartEmptyModel
@{
}

<h1>Do not have any bird in your cart</h1>
<a asp-page="HomePage">Return Home Page</a>

BirdFarmShop/Pages/CheckOut.cshtml
@page
@model BirdFarmShop.Pages.CheckOutModel
@{
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/cart.css">
    <title>Cart</title>
</head>
<body>
<h1>CheckInformation</h1>

<div class="cart_section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div class="cart_container">
                    <div class="cart_title">Shopping Cart<small> (1 item in your cart) </small></div>
                    <div class="cart_items">
                        <ul class="cart_list">
                            <form method="post" asp-page="cart" asp-page-handler="update">

                                @foreach (var item in Model.cart)
                                {
                                <li class="cart_item clearfix">
                                    <div class="cart_item_image"><img src="@item.bird.Image" alt=""></div>
                                    <div class="cart_item_info d-flex align-content-center flex-md-row justify-content-between">
                                        <div class="cart_item_name cart_info_col">
                                            <div class="cart_item_title">Name</div>
                                            <div class="cart_item_text">@item.bird.BirdName</div>
                                        </div>
                                        <div class="cart_item_quantity cart_info_col">
                                            <div class="cart_item_title">Quantity</div>

                                            <div class="cart_item_text"><input type="number" name="quantities" value="@item.Quantity" min="1" style="width: 50px;" /></div>
                                        </div>
                                        <div class="cart_item_price cart_info_col">
                                            <div class="cart_item_title">Price</div>
                                            <div class="cart_item_text">@item.bird.Price VNĐ</div>
                                        </div>
                                        <div class="cart_item_total cart_info_col">
                                            <div class="cart_item_title">Sub Total</div>
                                            <div class="cart_item_text">@(item.bird.Price * item.Quantity) VNĐ</div>
                                        </div>

                                        <div class="cart_item_total cart_info_col">
                                            <div class="cart_item_title"></div>
                                            <div class="cart_item_text"><input type="submit" value="Update" /><i class="fa-solid fa-code-compare"></i></div>
                                        </div>
                                        <div class="cart_item_total cart_info_col">
                                            <div class="cart_item_title"></div>
                                            <div class="cart_item_text"><a asp-page="cart" asp-page-handler="delete" asp-route-id="@item.bird.BirdId"><i class="fa-solid fa-trash"></i></a></div>
                                        </div>
                                    </div>
                                </li>
                                }
                            </form>
                        </ul>
                    </div>
                    <div class="order_total">
                        <div class="order_total_content text-md-right">
                            <div class="order_total_title">Order Total:</div>
                            <div class="order_total_amount">@Model.Total VNĐ</div>
                        </div>
                    </div>
                    <div class="cart_buttons">
                        <a asp-page="ShowAllBirds"><button type="button" class="button cart_button_clear">Continue Shopping</button></a>
                       @*  <a asp-page="CheckOut"><button type="button" class="button cart_button_checkout">Buy</button></a> *@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form method="post">
                @if (Model.Msg == null && Model.EmptyMsg == null)
                {
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="TblUser.FullName" class="control-label"></label>
                        <input asp-for="TblUser.FullName" class="form-control" />
                        <span asp-validation-for="TblUser.FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TblUser.Phone" class="control-label"></label>
                        <input asp-for="TblUser.Phone" class="form-control" />
                        <span asp-validation-for="TblUser.Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TblUser.UserAddress" class="control-label"></label>
                        <input asp-for="TblUser.UserAddress" class="form-control" />
                        <span asp-validation-for="TblUser.UserAddress" class="text-danger"></span>
                    </div>
                    <button type="submit" formaction="CheckOut">Check Out</button>

                }
                else if(Model.Msg != null)
                {
                    <h1 class="text-danger">@Model.Msg</h1>
                    <a asp-page="Login">Login Now</a>
                }
                else if(Model.EmptyMsg != null)
                {
                    <h1 class="text-danger">@Model.EmptyMsg</h1>
                    <a asp-page="ShowAllBirds">Continute Shopping</a>
                }
            </form>
        </div>
    </div>
<script src="https://kit.fontawesome.com/6bf3556146.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

BirdFarmShop/Pages/LoginGoogle.cshtml
@page
@model BirdFarmShop.Pages.LoginGoogleModel
@{
}

BirdFarmShop/Pages/LoginGoogleCallBack.cshtml
@page
@model BirdFarmShop.Pages.LoginGoogleCallBackModel
@{
}

BirdFarmShop/Pages/Logout.cshtml
@page
@model BirdFarmShop.Pages.LogoutModel
@{
}